### PR TITLE
pythoncapi_compat.h is MIT licensed

### PR DESCRIPTION
**Pull request by carlwgeorge**
The MIT license requires including the license and the copyright notice in copies of the software.  This file was pulled directly from the upstream repo.
    
https://github.com/pythoncapi/pythoncapi_compat/blob/main/COPYING

### CODE REVIEW

**Review by elprans — CHANGES_REQUESTED** [review]
The MIT license does not require the entire project to be relicensed in this manner, just the header file itself, which already contains the copyright header.  

The latest upstream version contains an SPDX identifier, so if we want to be formal here, I suggest putting that in the header file and placing the unmodified license text in the `licenses` directory like [the kernel does](https://github.com/torvalds/linux/blob/master/LICENSES/preferred/MIT)

**Comment by elprans** [comment]
Correction: the header file doesn't actually reference copyright holders directly.  @vstinner, it's probably a good idea to put "Copyright 2016, Red Hat, Inc. and Google Inc." in there, since the entire purpose of the file is to be copied into projects using the C API.

**Comment by vstinner** [comment]
Hi, I'm not a lawyer. Copyright and licenses are treated differently depending on countries. I'm not sure what is the current issue and how to fix it. I created https://github.com/pythoncapi/pythoncapi_compat/pull/9 : would you mind to review it?

**Comment by carlwgeorge** [comment]
> The MIT license does not require the entire project to be relicensed in this manner,

That's not what I'm suggesting.

> just the header file itself, which already contains the copyright header.

Per the MIT license (emphasis mine):

> > The above copyright notice and **this permission notice** shall be included
> > in all copies or substantial portions of the Software.

I am also not a lawyer, but what I typically see projects do is include all relevant license texts, either in separate files or concatenated into a single file, and indicate which files are under which license, either in another file or via header comments in each file.

**Comment by elprans** [comment]
> That's not what I'm suggesting.

That is what your PR is suggesting by putting an MIT license with a third-party copyright notice (which is apparently also invalid) at the top level of this project without qualifying which portions of the code it actually applies to.

I opened #65 to include the full text of the license in the header instead.

> I am also not a lawyer

None of us are lawyers, but there are guides on how to properly attribute permissively licensed bundled code: https://infra.apache.org/licensing-howto.html

**Comment by carlwgeorge** [comment]
> indicate which files are under which license, either in another file or via header comments in each file.

> at the top level of this project without qualifying which portions of the code it actually applies to

Feels like we're saying the same thing here. 😉

I knew this would be needed but I opened the PR anyways to get the project's feedback on how they wanted to do that.  Some project prefer headers in every file, as described in the appendix of the Apache license.

I've updated this PR to move the original license to LICENSE-APACHE and put a license breakdown in LICENSE.

**Pull request closed without merging**
